import { ThemeConfig } from './types';

export const themes: ThemeConfig[] = [
  {
    id: 'pixel',
    name: '像素勇者',
    description: '8bit 复古游戏风格，明亮像素色块',
    preview: '🎮',
    variables: {
      '--bg-primary': '#fce18a',
      '--bg-secondary': '#f5d06b',
      '--bg-card': '#fff8dc',
      '--text-primary': '#2e2e2e',
      '--text-secondary': '#5c5c5c',
      '--accent': '#e76e55',
      '--border-color': '#333333',
      '--border-glow': '#e76e55',
      '--progress-fill': '#e76e55',
      '--progress-bg': '#d4c5a0',
      '--success': '#4caf50',
      '--warning': '#ff9800',
      '--danger': '#f44336',
      '--font-mono': '"Press Start 2P", monospace',
      '--font-display': '"Press Start 2P", monospace',
      '--font-body': '"Press Start 2P", monospace',
    },
  },
  {
    id: 'terminal',
    name: '终端黑客',
    description: '绿屏终端，极客风范，CRT 扫描线',
    preview: '💻',
    variables: {
      '--bg-primary': '#0a0a0a',
      '--bg-secondary': '#0d1117',
      '--bg-card': '#111922',
      '--text-primary': '#00ff41',
      '--text-secondary': '#00cc33',
      '--accent': '#00ff41',
      '--border-color': '#00ff41',
      '--border-glow': '#00ff41',
      '--progress-fill': '#00ff41',
      '--progress-bg': '#1a2a1a',
      '--success': '#00ff41',
      '--warning': '#ffcc00',
      '--danger': '#ff4444',
      '--font-mono': '"Fira Code", "Courier New", monospace',
      '--font-display': '"Fira Code", monospace',
      '--font-body': '"Consolas", monospace',
    },
  },
  {
    id: 'arcane',
    name: '星界魔法',
    description: '魔法卷轴，紫金幻境，柔和发光',
    preview: '🌌',
    variables: {
      '--bg-primary': '#1a1025',
      '--bg-secondary': '#231535',
      '--bg-card': '#2a1a3e',
      '--text-primary': '#e0d7ff',
      '--text-secondary': '#b8a9d4',
      '--accent': '#c084fc',
      '--border-color': '#7c3aed',
      '--border-glow': '#c084fc',
      '--progress-fill': '#a78bfa',
      '--progress-bg': '#2d1b4e',
      '--success': '#6ee7b7',
      '--warning': '#fbbf24',
      '--danger': '#f87171',
      '--font-mono': '"Cinzel", serif',
      '--font-display': '"Cinzel", serif',
      '--font-body': '"Georgia", serif',
    },
  },
];

export function getThemeById(id: string): ThemeConfig | undefined {
  return themes.find((t) => t.id === id);
}